services:
  - type: web
    name: deepscalers-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn backend.wsgi:application -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: QDRANT_URL
        value: https://7775af46-4796-47d4-ab44-00c855e262f0.europe-west3-0.gcp.cloud.qdrant.io:6333
      - key: QDRANT_API_KEY
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: MAX_REQUESTS
        value: 1000
      - key: MAX_REQUESTS_JITTER
        value: 50 